### ISSUE TITLE
broken website

### ISSUE THREAD

**Issue by henryruss2** [noahpuckett99/noahpuckett99.github.io#1]
[https://awebsiteofcode.github.io] is not a website because it is not the name of the creator/organization of the repository.
you could fix that by going to settings > github pages > enable github pages or renaming your github account to awebsiteofcode.
Also, I forked your repo so it is at [henryruss2.github.io/noahpuckett.github.io].

**Comment by awebsiteofcode** [comment]
I know and can you please delete those forked repositories you forked to me please?!?
